### ISSUE TITLE
Consider increasing the number of iterations

### ISSUE THREAD

**Issue by Genbox** [RndPhrase/RndPhrase.js#23]
Browsers today have implemented PBKDF2 in C, and as such it is quite fast. 100 iterations does not take a lot of time, and you should consider increasing the number of iterations to 10.000 or more. For the optimal number of iterations, use [Performance.now()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) to measure how many milliseconds it takes to run X iterations. You should aim for 25 to 150 ms depending on the performance of your machine and the security level you want.

On my machine, 50.000 iterations takes around 30 ms, which is reasonable for a user to wait for a password to be derived.

**Comment by rlindsgaard** [comment]
Resolved by https://github.com/RndPhrase/RndPhrase.js/commit/31ec219a5a4e258880aba9de67bb0d8b069a2685
