### ISSUE TITLE
Version of 0 will result in 0 rounds

### ISSUE THREAD

**Issue by Genbox** [RndPhrase/RndPhrase.js#24]
With the code:
```javascript
self.version = parseInt(config.version);
if(isNaN(self.version) || self.version < 0) {
	self.version = 0;
}
```
Version will be set to 0. When the dprngFunction is called, it uses the following calculation `self.version*100`. When version = 0, it will result in rounds = 0, thereby reducing the security. It seems the behavior of 0 iterations depends on the browser - as far as I can tell with a quick look at the source, Gecko does 0 iterations and returns no output and Chromium gives an error.

### Suggested fix
In order to have a minimum amount of security, the number of iterations should always be above a minimum number of iterations. See #23 for my recommendations on the number of iterations. Either check that version is set and display an error if it is below 1, or guarantee a certain number of iterations by doing something like `rounds = math.Max(1000, version * 1000)`

**Comment by rlindsgaard** [comment]
Resolved by https://github.com/RndPhrase/RndPhrase.js/commit/cbdfb0bdbe21345008597aa8504a4dd1e35cc070
