### ISSUE TITLE
Reduction of entropy in uint8 conversion

### ISSUE THREAD

**Issue by Genbox** [RndPhrase/RndPhrase.js#25]
When converting between strings and byte arrays (uint8 arrays), we need to take the encoding of the string into consideration in order to keep the entropy of the string. In your case, you have the following function:

```javascript
var str2ab = function(str) {
    var buf = new ArrayBuffer(str.length);
    var bufView = new Uint8Array(buf);
    for (var i = 0; i < str.length; i += 1) {
          bufView[i] = str.charCodeAt(i);
     }
    return buf;
};
```
The way this function might not be as expected due to several factors:

charCodeAt() returns a UTF-16 char code, which is a number between 0 and 65535. 16 bit is 2 bytes, which is not enough to represent all the characters in the Unicode set. Since Javascript uses UTF-16 for internal string representation, it needs to create so called surrogate pairs that are more than 2 bytes in size to represent all characters. Since the function assumes that 1 byte = 1 character, 2 things happen:
   a. It truncates code points outside the range 0-255
   b. Surrogate pairs does not get included at all. 

So for simple ASCII strings and UTF-8 string with a code point value below 128, this works fine:
- str2ab("test") = { 116, 101, 115, 116 }
- str2ab("!") = { 49 }

However, when we input characters above code point 255, we get the wrong results:
- str2ab("中") = { 45 } (which is '-' in ASCII)
- str2ab("ź") = { 112 } (which is 'z' in ASCII)

When it comes to entropy and security, this is not good as we effectively reduce the security of a password by an order of magnitude, when the password is not using ASCII.

### Suggested fix
The only solution here is to use Unicode when converting the password to bytes. In order to represent as many characters as possible, as well as save space while maintaining ASCII backwards compatibility (which is important in this case, since all old passwords generated with this code, would otherwise be invalid after the fix), we could use UTF-8 in combination with the [Text Encoding Specification](https://encoding.spec.whatwg.org/). In JavaScript, this is implemented as the TextEncoder and TextDecoder interfaces. We can now change the str2ab function to this:
```javascript
var str2ab = function(str) {
	return new TextEncoder("utf-8").encode(str);
};
```
Let's check the results of it:
- str2ab("中") = { 228, 184, 173 } (3 bytes, which is correct)
- str2ab("ź") = { 197, 186 } (2 bytes, which is correct)

A quick note about the backwards compatability is that both functions (old and new str2ab) returns the same values for ASCII characters. Example:
- str2abOld("a") = 97
- str2abNew("a") = 97

Note that this issue not only applies to passwords, but also the salt that is generated using the same str2ab function. It therefore also reduces the entropy of the salt, which is not as severe as the password, but worth correcting in any case.

**Comment by rlindsgaard** [comment]
Resolved https://github.com/RndPhrase/RndPhrase.js/commit/9886d715a89eba250dec101c275e71b87345636e
